Card 6.1
wolox-training/ll-react-native pull request #3
Opened 2022-07-11 20:25 UTC by lauuta185

## Summary

[Change!] I make a "Book component" whit their styles.

## Screenshots

[Change!] 
<img width="1536" alt="Screen Shot 2022-07-11 at 17 23 11" src="https://user-images.githubusercontent.com/108479534/178351879-84a684d4-e4da-4704-9f25-38b8eddd1df0.png">
<img width="1536" alt="Screen Shot 2022-07-11 at 17 23 28" src="https://user-images.githubusercontent.com/108479534/178351894-3fb4aa8e-5ba0-4f7c-8fdc-10f952ae062e.png">

### Android

#### Galaxy S (or similar)

#### Pixel 2/3 (or similar)

#### Pixel 3XL (or similar)

### iOS

#### iPhone SE (or similar)

#### iPhone 6/7/8 (or similar)

#### iPhone 11/12 Base/Pro/Pro Max (or similar)

## Trello Card

[Change!] Link to the associated Trello card.

2022-07-11 20:32 UTC, DiegoQuiros94 commented on wbooks/src/app/screens/Home/styles.ts
> +  title: {
you can remove this if you are not using it

2022-07-11 20:33 UTC, DiegoQuiros94 commented on wbooks/src/app/screens/Home/index.tsx
> +import Book from '@app/components/Book';
you can use @components

2022-07-11 21:15 UTC, andreszuluaga-wolox requested changes

2022-07-11 21:15 UTC, andreszuluaga-wolox commented on wbooks/src/app/components/Book/index.tsx
> +      <Image source={imageUrl} />
the image should has styles

2022-07-11 21:15 UTC, andreszuluaga-wolox commented on wbooks/src/app/components/Book/styles.ts
> +    left: '115%',
is it necessary?

2022-07-11 21:15 UTC, andreszuluaga-wolox commented on wbooks/src/app/screens/Home/styles.ts
> +import { grey } from '@constants/colors';
this color exist in de colors file?

2022-07-11 21:15 UTC, andreszuluaga-wolox commented on wbooks/src/constants/colors.ts
> +export const titleColor = '#474747';
no use name from element, use color name

2022-07-11 21:23 UTC, DiegoQuiros94 requested changes

2022-07-11 21:23 UTC, DiegoQuiros94 commented on wbooks/src/app/components/Book/styles.ts
> +    right: '350%',
this is not correct, you should not need to hard code the position

2022-07-11 21:23 UTC, DiegoQuiros94 commented on wbooks/src/app/components/Book/styles.ts
> +    flexDirection: 'row',
why are you setting this as row? the text container should be column, since it goes in vertical direction

2022-07-11 21:23 UTC, DiegoQuiros94 commented on wbooks/src/app/components/Book/styles.ts
> +    top: 20,
this is also wrong, you won't need this if you correct the direction

2022-07-11 21:23 UTC, DiegoQuiros94 commented on wbooks/src/app/components/Book/styles.ts
> +    display: 'flex',
this is the default value, you don't need to specify it

2022-07-11 21:23 UTC, DiegoQuiros94 commented on wbooks/src/app/components/Book/styles.ts
> +    textAlign: 'center',
if you check figma the text is aligned to the left

2022-07-12 14:15 UTC, DiegoQuiros94 commented on wbooks/src/app/components/Book/styles.ts
> +    padding: '3%'
use fixed values for margin/paddings

2022-07-13 19:02 UTC, DiegoQuiros94 approved these changes

2022-07-13 19:02 UTC, DiegoQuiros94 commented on wbooks/src/app/components/Book/styles.ts
> +
remove extra space

2022-07-13 20:24 UTC, merged